### ISSUE TITLE
文档优化建议

### ISSUE THREAD

**Issue by cj0x39e** [aliyun/alibabacloud-push-flutter-plugin#15]
https://github.com/aliyun/alibabacloud-push-flutter-plugin/blob/093fd359bb0618893cdb1ac2743e3c735ed03291/README.md?plain=1#L159

因为华为的id 配置如下：
```xml
<meta-data
	android:name="com.huawei.hms.client.appid"
 	android:value="appid=xxxxxx" />
```

华为这个值配置时要加`appid=`，这个最好在 README 里面特别说明下，容易踩坑。

**Comment by wangyun137** [comment]
感谢建议
