### ISSUE TITLE
release 模式下 initPush 就会直接 crash

### ISSUE THREAD

**Issue by jhfkf** [aliyun/alibabacloud-push-flutter-plugin#4]
logcat上面给的是这个错误  
No pending exception expected: java.lang.NoSuchMethodError: no static or non-static method "Lorg/android/spdy/SpdyAgent;.freeAgent(J)I"'

**Comment by jhfkf** [comment]
是混淆代码的错误吗  增加插件后 包体积增加很多

**Comment by liuchaowei666** [comment]
你好，这个解决了吗
