### ISSUE TITLE
ios端前台与后台返回数据格式不统一

### ISSUE THREAD

**Issue by cove1205** [aliyun/alibabacloud-push-flutter-plugin#8]
ios端在前台收到通知时将userinfo的字段拆分了出来拼成一个字典传出。而点击通知栏进入应用触发回调didReceiveNotificationResponse时则是直接将userinfo传回来，导致2种方式获得的数据结构不统一，用户需要额外进行数据处理。

另外在2种方式返回的数据中，都只从iOSExtParameters中截取"Extras"这个固定字段返回，导自定义其他的key值无法被用户接收到。并且前后台两种方式回调“extras”的首字符大小写还不同。。。

**Comment by wangyun137** [comment]
已合并，感谢
